  language: python
  services:
    - docker
  python:
    - "2.7"
  install:
    - make deps
  script:
    - make test
    - make test_xunit
    - make lint
    - make docker_build
    - make docker_run
    - sleep 2; python test-api/api_test.py
  after_success:
    - make docker_push
  deploy:
    provider: heroku
    app: shielded-reef-85462
    api_key: ${HEROKU_API_KEY}
