  dist: trusty
  addons:
    apt:
      packages:
        - google-chrome-stable
  language: python
  services:
    - docker
  python:
    - "2.7"
  install:
    - make deps
  before_install:
    - google-chrome-stable --headless  --no-sandbox --disable-gpu
  before_script:
    - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/bin/
  script:
    - make test
    - make test_xunit
    - make test_cov
    - make lint
    - make docker_build
    - make docker_run
    - sleep 2; make test-api
    - sleep 3; make test_ui
  after_success:
    - make codeclimate
    - make docker_push
  deploy:
    provider: heroku
    app: shielded-reef-85462
    api_key: ${HEROKU_API_KEY}
