  language: python
  services:
    - docker
  python:
    - "2.7"
  install:
    - make deps
  before_script:
    - wget http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.14/bin/
    - export CHROME_BIN=chromium-browser
  script:
    - make test
    - make test_xunit
    - make test_codeclimate
    - make lint
    - make docker_build
    - make docker_run
    - sleep 2; make test-api
  after_success:
    - make docker_push
    - make codeclimate
  deploy:
    provider: heroku
    app: shielded-reef-85462
    api_key: ${HEROKU_API_KEY}
