  language: python
  services:
    - docker
  python:
    - "2.7"
  install:
    - make deps
  before_script:
  script:
    - make test
    - make test_xunit
    - make test_cov
    - make lint
    - make docker_build
    - make docker_run
    - sleep 2; make test-api
    - sleep 3; xvfb-run --server-args="-screen 0 1024x768x24" make test_ui
  after_success:
    - make codeclimate
    - make docker_push
  deploy:
    provider: heroku
    app: shielded-reef-85462
    api_key: ${HEROKU_API_KEY}
